fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    epel:
      repo: https://github.com/voxpupuli/puppet-epel.git
    rhsm:
      repo: https://github.com/voxpupuli/puppet-rhsm
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    vcsrepo:
      repo: https://github.com/puppetlabs/puppetlabs-vcsrepo.git
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache.git
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
    augeasproviders_core:
      repo: https://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: https://github.com/hercules-team/augeasproviders_shellvar.git
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
    logrotate:
      repo: https://github.com/voxpupuli/puppet-logrotate.git
  symlinks:
    openondemand: "#{source_dir}"
